apiVersion: v1
kind: Service
metadata:
  annotations:
    strategy.spinnaker.io/versioned: 'false'
  labels:
    name: minio-operator
  name: operator
spec:
  ports:
    - name: https
      port: 4222
    - name: http
      port: 4221
  selector:
    name: minio-operator
    operator: leader
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
spec:
  replicas: 2
  selector:
    matchLabels:
      name: minio-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
      labels:
        name: minio-operator
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - minio-operator
              topologyKey: kubernetes.io/hostname
      containers:
        - image: 'minio/operator:v4.4.23'
          imagePullPolicy: IfNotPresent
          name: minio-operator
          resources:
            requests:
              cpu: 200m
              ephemeral-storage: 500Mi
              memory: 256Mi
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
      serviceAccountName: minio-operator
