apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: console-sa
    strategy.spinnaker.io/versioned: 'false'
  name: console-sa-secret
type: kubernetes.io/service-account-token

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    strategy.spinnaker.io/versioned: 'false'
  labels:
    name: console
  name: console
spec:
  ports:
    - name: http
      port: 9090
    - name: https
      port: 9443
  selector:
    app: console
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
      labels:
        app: console
    spec:
      containers:
        - args:
            - server
          env:
            - name: CONSOLE_OPERATOR_MODE
              value: 'on'
          image: 'minio/console:v0.18.1'
          imagePullPolicy: IfNotPresent
          name: console
          ports:
            - containerPort: 9090
              name: http
            - containerPort: 9433
              name: https
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
      serviceAccountName: console-sa
